name: scorecard-be

services:
  app:
    image: iblgroup/searle-scorecard-be:1.0.0
    container_name: searle-scorecard-be
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.docker
    ports:
      - "3005:3005"
    volumes:
      - ./logs:/app/logs
